#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

#------------------------------- nanoFluid4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

wmake libso src/thermophysicalModels/specie
wmake libso src/thermophysicalModels/basic
applications/Allwmake

# ----------------------------------------------------------------- end-of-file
