#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- hemodynamic4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cleancase is function that removes the files and directories.(rm -f : remove the file, rm -r : remove the directory).
cleancase ()
{
    rm -r Gnu*
    rm -r processor*
}


postProcess ()
{
    helicity4HD
    LNH4HD
    TAH4HD
    TAHI4HD
    WSS4HD
    magWSS4HD
    TAWSS4HD
    magTAWSS4HD
    OSI4HD
    RRT4HD
}

# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

#cleancase
./Allclean


echo run blockMesh ...
blockMesh
#checkMesh

#To create porous zone
# it can be used to create one zone
#cellSet
#setsToZones

# it can be used to create multi zones
rm -rf constant/polyMesh/sets
setSet -batch makeCellSets.setSet
rm constant/polyMesh/sets/*_old
setsToZones -noFlipMap
splitMeshRegions -cellZones -overwrite

mkdir -p 0.001/chamber
mkdir -p 0.001/leftSolid
mkdir -p 0.001/rightSolid

cp 0/* 0.001/chamber/
cp 0/* 0.001/leftSolid/
cp 0/* 0.001/rightSolid/

changeDictionary -region chamber
changeDictionary -region leftSolid
changeDictionary -region rightSolid



echo run solver ...
chtMultiRegionPCMFoam
#$application

paraFoam -touchAll

# -------------------------------------------------------------------------- end-of-file






